[package]
name = "secret-santa-rs"
version = "0.1.0"
authors = ["Yagora <tanguy.charon47@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10.0-alpha.4"
serde = "0.9"
serde_yaml = "0.6"